name: termdo

services:
  db:
    build: .
    restart: unless-stopped
    container_name: termdo-db
    volumes:
      - ./data/:/var/lib/postgresql/data/
    env_file: .env

networks:
  default:
    name: termdo-net
